build-backend-code-job:
  stage: build
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - python -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest

  cache:
    key: pip-cache
    policy: pull-push
    paths:
      - .venv
      - backend/__pycache__

  artifacts:
    paths:
      - backend/__pycache__
    expire_in: 1 week
